export const sampleConversations = [
  { id: "1", title: "What is the total revenue by country?", time: "2 mins ago" },
  { id: "2", title: "Filter that by 2024", time: "8 mins ago" },
  { id: "3", title: "Top 10 customers by spend", time: "15 mins ago" },
  { id: "4", title: "Monthly revenue trend", time: "1 hour ago" },
  { id: "5", title: "Top selling tracks", time: "2 hours ago" },
];

export const sampleQueries = {
  "1": {
    question: "What is the total revenue by country?",
    time: "2:31 PM",
    intent: "Analytical",
    mode: "Hybrid (RAG + TAG)",
    sources: "Sources: 8 docs, 12 tables",
    stats: [
      { label: "Total Revenue", value: "$2,476.10", icon: "dollar", color: "purple" },
      { label: "Countries", value: "22", icon: "globe", color: "blue" },
      { label: "Top Country", value: "USA ($523.06)", icon: "trending", color: "green" },
      { label: "Query Time", value: "812 ms", icon: "clock", color: "orange" },
    ],
    columns: [
      { key: "country", label: "country" },
      { key: "total_revenue", label: "total_revenue" },
    ],
    data: [
      { country: "USA", total_revenue: "$523.06" },
      { country: "Canada", total_revenue: "$303.96" },
      { country: "France", total_revenue: "$195.10" },
      { country: "Brazil", total_revenue: "$190.10" },
      { country: "Germany", total_revenue: "$156.48" },
      { country: "United Kingdom", total_revenue: "$112.86" },
      { country: "Czech Republic", total_revenue: "$90.24" },
      { country: "Portugal", total_revenue: "$77.24" },
      { country: "India", total_revenue: "$75.26" },
      { country: "Chile", total_revenue: "$46.62" },
      { country: "Ireland", total_revenue: "$45.62" },
      { country: "Hungary", total_revenue: "$45.62" },
      { country: "Austria", total_revenue: "$42.62" },
      { country: "Finland", total_revenue: "$41.62" },
      { country: "Netherlands", total_revenue: "$40.62" },
      { country: "Norway", total_revenue: "$39.62" },
      { country: "Sweden", total_revenue: "$38.62" },
      { country: "Spain", total_revenue: "$37.62" },
      { country: "Poland", total_revenue: "$37.62" },
      { country: "Italy", total_revenue: "$37.62" },
      { country: "Belgium", total_revenue: "$37.62" },
      { country: "Argentina", total_revenue: "$37.62" },
    ],
    totalLabel: "countries",
  },
  "2": {
    question: "Filter that by 2024",
    time: "2:33 PM",
    intent: "Filter",
    mode: "Hybrid (RAG + TAG)",
    sources: "Sources: 3 docs, 4 tables",
    stats: [
      { label: "2024 Revenue", value: "$1,204.55", icon: "dollar", color: "purple" },
      { label: "Countries", value: "18", icon: "globe", color: "blue" },
      { label: "Top Country", value: "USA ($267.30)", icon: "trending", color: "green" },
      { label: "Query Time", value: "645 ms", icon: "clock", color: "orange" },
    ],
    columns: [
      { key: "country", label: "country" },
      { key: "total_revenue", label: "total_revenue_2024" },
    ],
    data: [
      { country: "USA", total_revenue: "$267.30" },
      { country: "Canada", total_revenue: "$152.10" },
      { country: "France", total_revenue: "$98.50" },
      { country: "Brazil", total_revenue: "$95.20" },
      { country: "Germany", total_revenue: "$78.40" },
      { country: "United Kingdom", total_revenue: "$56.40" },
      { country: "Czech Republic", total_revenue: "$45.12" },
      { country: "Portugal", total_revenue: "$38.62" },
      { country: "India", total_revenue: "$37.63" },
      { country: "Chile", total_revenue: "$23.31" },
      { country: "Ireland", total_revenue: "$22.81" },
      { country: "Hungary", total_revenue: "$22.81" },
      { country: "Austria", total_revenue: "$21.31" },
      { country: "Finland", total_revenue: "$20.81" },
      { country: "Netherlands", total_revenue: "$20.31" },
      { country: "Norway", total_revenue: "$19.81" },
      { country: "Sweden", total_revenue: "$19.31" },
      { country: "Spain", total_revenue: "$18.81" },
    ],
    totalLabel: "countries",
  },
  "3": {
    question: "Top 10 customers by spend",
    time: "2:28 PM",
    intent: "Ranking",
    mode: "Hybrid (RAG + TAG)",
    sources: "Sources: 5 docs, 8 tables",
    stats: [
      { label: "Total Spend", value: "$523.06", icon: "dollar", color: "purple" },
      { label: "Avg Spend", value: "$52.31", icon: "globe", color: "blue" },
      { label: "Top Customer", value: "Helena Holy", icon: "trending", color: "green" },
      { label: "Query Time", value: "523 ms", icon: "clock", color: "orange" },
    ],
    columns: [
      { key: "customer", label: "customer_name" },
      { key: "email", label: "email" },
      { key: "total_spend", label: "total_spend" },
    ],
    data: [
      { customer: "Helena Holy", email: "hholy@gmail.com", total_spend: "$49.62" },
      { customer: "Richard Cunningham", email: "ricunningham@gmail.com", total_spend: "$47.62" },
      { customer: "Luis Rojas", email: "luisrojas@yahoo.cl", total_spend: "$46.62" },
      { customer: "Ladislav Kovacs", email: "ladislav@cz.net", total_spend: "$45.62" },
      { customer: "Hugh O'Reilly", email: "hughoreilly@ie.net", total_spend: "$45.62" },
      { customer: "Frank Ralston", email: "fralston@gmail.com", total_spend: "$43.62" },
      { customer: "Fynn Zimmermann", email: "fzimmer@de.net", total_spend: "$43.62" },
      { customer: "Astrid Gruber", email: "astrid.gruber@apple.at", total_spend: "$42.62" },
      { customer: "Mark Philips", email: "mphilips12@shaw.ca", total_spend: "$42.62" },
      { customer: "Roberto Almeida", email: "roberto.almeida@br.net", total_spend: "$42.62" },
    ],
    totalLabel: "customers",
  },
};